### ISSUE TITLE
Layout Bug on Pricing Page 

### ISSUE THREAD

**Issue by SlowMoschen** [Litlyx/litlyx#1]
Hey, I found a responsiveness Bug on the pricing page for mobile devices.

Even after reloading the Page, the bug still occurs. 

![Screenshot_20240605_111227_com.android.chrome.jpg](https://github.com/Litlyx/litlyx/assets/122015710/ff1ed7c1-471c-464b-bb98-af92276197fd)

![Screenshot_20240605_104902_com.android.chrome.jpg](https://github.com/Litlyx/litlyx/assets/122015710/7477a765-4365-44c4-bec3-43dddffd4454)

**Comment by Litlyx** [comment]
Thanks for the feedback we will fix today 🙏

**Comment by Litlyx** [comment]
Fixed in [7e8da6e](https://github.com/Litlyx/litlyx/commit/7e8da6ec06a96ae1c500ddc666e5ed7e70de5b80)
