### ISSUE TITLE
[proposal/question] Shouldn't the event endpoint be used for visit events?

### ISSUE THREAD

**Issue by MaximalCats** [Litlyx/litlyx#14]
Why is a separate visit endpoint needed, can't we just use /event? 
e.g.

```
fetch('/event', {method: "POST", body: JSON.stringify({
  name: "visit",
  website: location.host,
  page: location.pathname,
  referrer: document.referrer
})})

```
Relevant: https://github.com/Litlyx/litlyx/blob/main/producer/src/index.ts#L31

**Comment by AntonioVerdiglione1996** [comment]
For code design reasons, we have decided to keep them separate, as we handle visits and events in our database independently.
