### ISSUE TITLE
Feature Request: Block Development IPs from Analytics

### ISSUE THREAD

**Issue by fr0st-iwnl** [Litlyx/litlyx#20]
Hi! I’ve noticed that my **Litlyx Analytics** is showing traffic from local development IPs like `127.0.0.1`, which is affecting the accuracy of my analytics. It would be really helpful if the platform could automatically block certain IPs that are commonly used in development or testing, such as `127.0.0.1` and other local network addresses. This would help remove internal traffic from the analytics and show more accurate data for real users.

![241106_04h45m44s_screenshot](https://github.com/user-attachments/assets/ca33270c-f26c-4aa7-901e-c1eb1e30bcc2)

**Comment by AntonioVerdiglione1996** [comment]
We have released the new data tab in settings that allow you to clean your development IP's. Try it and let us know what you think!

**Comment by fr0st-iwnl** [comment]
i love it! :) it works perfectly

> We have released the new data tab in settings that allow you to clean your development IP's. Try it and let us know what you think!
