### ISSUE TITLE
Embeddable Unique Visitors Counter

### ISSUE THREAD

**Issue by christmaswreath** [Litlyx/litlyx#22]
Like this image except nicer-looking ![image](https://github.com/user-attachments/assets/c465bcc9-6d4d-4d1d-a5f8-b40528583362)
And also a little 88x31 size one
Or like this ![image](https://github.com/user-attachments/assets/1c8e4397-fac9-4a5a-8bc2-0c587beeb2a3)

**Comment by christmaswreath** [comment]
Yes, that's correct! The biggest issue with having a normal visits counter is when I reload my webpage after updating it, it would count as a hit and update the counter. That's not a very accurate representation of how many unique people have visited the web page. An 88 by 31 button is a small button, ex. these I have designed. ![proxmox](https://github.com/user-attachments/assets/7ee33fe2-d308-409d-8542-a6d60104310c)![caddy](https://github.com/user attachments/assets/7d5d9367-aa04-4348-9883-e3745b644991) They would be easy to integrate into my webpage since I also have a series of other 88 by 31 buttons, however they do not have to be 88 by 31 pixels, they just have to have the width factor of 88 by 31. I use a DPI monitor and fractional scaling meaning that if the image is 88 by 31 pixels it's actually larger than that, or so I believe. Sorry if I'm being hard to understand.

**Comment by christmaswreath** [comment]
But also, larger and more verbose widgets would be useful for websites that don't look like they came from the early 2000s.

**Comment by AntonioVerdiglione1996** [comment]
Let's move this chat in the discussions tab on github!
