### ISSUE TITLE
Error occurs when creating new project after user registration

### ISSUE THREAD

**Issue by perisicnikola37** [Litlyx/litlyx#3]
## 🚨 Technical Bug Report
Hello there 😃 

I would like to bring to your attention an issue I encountered while registering on your platform. Upon registration, I was redirected to a new project creation page. However, upon attempting to submit the form, I consistently encountered a JavaScript alert displaying the following message: "`Cannot read properties of undefined (reading '_id')`".

![bug_case_of_registering_a_new_project](https://github.com/Litlyx/litlyx/assets/79047182/801ddfaa-640f-4305-a71a-11e09aca68fa)

<hr />

I solved it by going to `https://dashboard.litlyx.com/` directly. However, this bug issue exists and should be resolved 😄

**Comment by Litlyx** [comment]
We will fix it today! I've seen your email, i will come back to you soon! Thanks a lot for your feedback!
