### ISSUE TITLE
Ux bug, clicking on +New Chat doesn't work when there is no chat history

### ISSUE THREAD

**Issue by slim-python** [Litlyx/litlyx#8]
Hello there 😃

I would like to bring to your attention an ux issue I encountered while registering on your platform. after registration, i clicked on +New chat button in the left and it didn't do anything when there was no recent chats, instead it shouldn't show this button in my opinion

os: windows 11
browser: edge

if you want i can fix it with a small pr
![image](https://github.com/Litlyx/litlyx/assets/55599278/703c6252-09c4-48d1-b52d-4fa2bfdb335c)

**Comment by AntonioVerdiglione1996** [comment]
Thanks a lot for your feedback. We will fix it in the near future.

**Comment by prathamjagga** [comment]
Since the chats dont have any names for now, I don't think it is needed to have multiple empty chats with no identity. So it is better as it is now.

**Comment by AntonioVerdiglione1996** [comment]
I close this issue because we had a deliberated choice to mantain the current state of the AI Chat. We will be soon changing design of our platform. Stay tuned!
