### ISSUE TITLE
[UX Enhancement] Show More Table Layouts for the Top Countries to have flags in table like Top Referrers

### ISSUE THREAD

**Issue by smadixd** [Litlyx/litlyx#9]
Show More for Top Countries:
![image](https://github.com/user-attachments/assets/4dba3b16-439e-4a41-adfb-4242e511da21)

Show More for Top Referrers:
![image](https://github.com/user-attachments/assets/18a2dd70-5368-4dc8-ba62-6de2892ea3a7)

Expected behaviour:

Make show more table always include icon/flag if exists for each row.

**Comment by siddharthisrani** [comment]
Hii @AntonioVerdiglione1996 Can i work on this issue?

**Comment by AntonioVerdiglione1996** [comment]
Sure, fork the repo, do a new branch and go! I will review your PR.

**Comment by siddharthisrani** [comment]
Hii @AntonioVerdiglione1996 Yes working on it!

**Comment by harnoor-gandhi** [comment]
@AntonioVerdiglione1996 @smadixd 
How are we gonna give favicons to urls that we are giving dummy icon just for now in top referrers table ?

**Comment by siddharthisrani** [comment]
Hii @AntonioVerdiglione1996  I’m currently facing an issue with running the API endpoint "https://dashboard.litlyx.com/live_demo" on my local environment. I need to verify whether the issue has been resolved. Could you please assist me with this?

**Comment by AntonioVerdiglione1996** [comment]
Here the link to join Dicord: https://discord.gg/9cQykjsmWX

**Comment by AntonioVerdiglione1996** [comment]
@harnoor-gandhi Sorry i lost your comment before. Can you explain in details what you mean with 'use Amazon S3 to store favicons' ? What is the concern?
